# Generated by Django 4.2.23 on 2025-07-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudo_app', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(help_text='Organization associated with the User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='kudo_app.organization'),
        ),
    ]
