# Generated by Django 4.2.23 on 2025-07-30 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudo_app', '0004_kudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyKudoTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('kudos_given', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudo_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kudo tracker',
                'verbose_name_plural': 'Kudo tracker',
                'db_table': 'weekly_kudo_tracker',
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
